# Generated by Django 5.2.15 on 2026-07-01 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightMomentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_sec', models.FloatField()),
                ('tipo', models.CharField(choices=[('gol', 'Gol'), ('defesa', 'Defesa'), ('penalti', 'Pênalti'), ('falta', 'Falta'), ('expulsao', 'Expulsão'), ('chance', 'Chance'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('importancia', models.IntegerField(default=0)),
                ('included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'studio_highlight_moment',
                'ordering': ['timestamp_sec'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='thumbnailmodel',
            name='unique_project_variant',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='highlight_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_type',
            field=models.CharField(choices=[('gopro', 'Go Pro'), ('futebol', 'Futebol')], default='gopro', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('merge', 'Merge'), ('highlight_detect', 'Detecção de Highlights'), ('export', 'Export'), ('thumbnail', 'Thumbnail'), ('seo', 'SEO'), ('publish', 'Publicar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='phase',
            field=models.CharField(choices=[('new', 'Novo'), ('sources_uploaded', 'Fontes Enviadas'), ('merge_done', 'Merge Concluído'), ('highlights_done', 'Highlights Detectados'), ('export_done', 'Export Pronto'), ('thumbnails_done', 'Thumbnails OK'), ('seo_approved', 'SEO Aprovado'), ('published', 'Publicado')], default='new', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnailmodel',
            unique_together={('project', 'variant')},
        ),
        migrations.AddField(
            model_name='highlightmomentmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_moments', to='studio.projectmodel'),
        ),
        migrations.AddField(
            model_name='highlightmomentmodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_moments', to='studio.sourcemodel'),
        ),
    ]
