# Generated by Django 5.2.15 on 2026-07-02 02:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_highlightmomentmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightClipModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_sec', models.FloatField()),
                ('end_sec', models.FloatField()),
                ('order', models.IntegerField(default=0)),
                ('included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_clips', to='studio.projectmodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_clips', to='studio.sourcemodel')),
            ],
            options={
                'db_table': 'studio_highlight_clip',
                'ordering': ['order'],
            },
        ),
    ]
