# Generated by Django 5.2.15 on 2026-07-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_highlightclipmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('merge', 'Merge'), ('highlight_detect', 'Detecção de Highlights'), ('highlight_recut', 'Recorte de Highlights'), ('export', 'Export'), ('thumbnail', 'Thumbnail'), ('seo', 'SEO'), ('publish', 'Publicar')], max_length=20),
        ),
    ]
